server:
  port: 8080

logging:
  pattern:
    console:

spring:
  application:
    name: DepositService
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        enabled: true
        path: /mcp
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: false
  datasource:
    url: jdbc:h2:mem:depositDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  redis:
    host: 127.0.0.1
    port: 6379

